//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMICGOR.HobbitsWCFService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stats", Namespace="http://schemas.datacontract.org/2004/07/ObjectManager.Models")]
    [System.SerializableAttribute()]
    public partial class Stats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gold {
            get {
                return this.GoldField;
            }
            set {
                if ((this.GoldField.Equals(value) != true)) {
                    this.GoldField = value;
                    this.RaisePropertyChanged("Gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HobbitsWCFService1.IHobbits")]
    public interface IHobbits {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/CreatePlayer", ReplyAction="http://tempuri.org/IHobbits/CreatePlayerResponse")]
        int CreatePlayer(string name, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/CreatePlayer", ReplyAction="http://tempuri.org/IHobbits/CreatePlayerResponse")]
        System.Threading.Tasks.Task<int> CreatePlayerAsync(string name, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayer", ReplyAction="http://tempuri.org/IHobbits/GetPlayerResponse")]
        int GetPlayer(string name, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayer", ReplyAction="http://tempuri.org/IHobbits/GetPlayerResponse")]
        System.Threading.Tasks.Task<int> GetPlayerAsync(string name, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayerName", ReplyAction="http://tempuri.org/IHobbits/GetPlayerNameResponse")]
        string GetPlayerName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayerName", ReplyAction="http://tempuri.org/IHobbits/GetPlayerNameResponse")]
        System.Threading.Tasks.Task<string> GetPlayerNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayerStats", ReplyAction="http://tempuri.org/IHobbits/GetPlayerStatsResponse")]
        GameMICGOR.HobbitsWCFService1.Stats GetPlayerStats(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbits/GetPlayerStats", ReplyAction="http://tempuri.org/IHobbits/GetPlayerStatsResponse")]
        System.Threading.Tasks.Task<GameMICGOR.HobbitsWCFService1.Stats> GetPlayerStatsAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHobbitsChannel : GameMICGOR.HobbitsWCFService1.IHobbits, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HobbitsClient : System.ServiceModel.ClientBase<GameMICGOR.HobbitsWCFService1.IHobbits>, GameMICGOR.HobbitsWCFService1.IHobbits {
        
        public HobbitsClient() {
        }
        
        public HobbitsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HobbitsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbitsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbitsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreatePlayer(string name, string code) {
            return base.Channel.CreatePlayer(name, code);
        }
        
        public System.Threading.Tasks.Task<int> CreatePlayerAsync(string name, string code) {
            return base.Channel.CreatePlayerAsync(name, code);
        }
        
        public int GetPlayer(string name, string code) {
            return base.Channel.GetPlayer(name, code);
        }
        
        public System.Threading.Tasks.Task<int> GetPlayerAsync(string name, string code) {
            return base.Channel.GetPlayerAsync(name, code);
        }
        
        public string GetPlayerName(int id) {
            return base.Channel.GetPlayerName(id);
        }
        
        public System.Threading.Tasks.Task<string> GetPlayerNameAsync(int id) {
            return base.Channel.GetPlayerNameAsync(id);
        }
        
        public GameMICGOR.HobbitsWCFService1.Stats GetPlayerStats(string name) {
            return base.Channel.GetPlayerStats(name);
        }
        
        public System.Threading.Tasks.Task<GameMICGOR.HobbitsWCFService1.Stats> GetPlayerStatsAsync(string name) {
            return base.Channel.GetPlayerStatsAsync(name);
        }
    }
}
