//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMICGOR.DragonCaveService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Treasure", Namespace="http://schemas.datacontract.org/2004/07/ObjectManager.Models")]
    [System.SerializableAttribute()]
    public partial class Treasure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gold {
            get {
                return this.GoldField;
            }
            set {
                if ((this.GoldField.Equals(value) != true)) {
                    this.GoldField = value;
                    this.RaisePropertyChanged("Gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DragonCaveService1.IDragonCave")]
    public interface IDragonCave {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDragonCave/GetLoot", ReplyAction="http://tempuri.org/IDragonCave/GetLootResponse")]
        GameMICGOR.DragonCaveService1.Treasure GetLoot(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDragonCave/GetLoot", ReplyAction="http://tempuri.org/IDragonCave/GetLootResponse")]
        System.Threading.Tasks.Task<GameMICGOR.DragonCaveService1.Treasure> GetLootAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDragonCaveChannel : GameMICGOR.DragonCaveService1.IDragonCave, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DragonCaveClient : System.ServiceModel.ClientBase<GameMICGOR.DragonCaveService1.IDragonCave>, GameMICGOR.DragonCaveService1.IDragonCave {
        
        public DragonCaveClient() {
        }
        
        public DragonCaveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DragonCaveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DragonCaveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DragonCaveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameMICGOR.DragonCaveService1.Treasure GetLoot(int value) {
            return base.Channel.GetLoot(value);
        }
        
        public System.Threading.Tasks.Task<GameMICGOR.DragonCaveService1.Treasure> GetLootAsync(int value) {
            return base.Channel.GetLootAsync(value);
        }
    }
}
