//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMICGOR.CaveService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/ObjectManager.Models")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Center {
            get {
                return this.CenterField;
            }
            set {
                if ((object.ReferenceEquals(this.CenterField, value) != true)) {
                    this.CenterField = value;
                    this.RaisePropertyChanged("Center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Down {
            get {
                return this.DownField;
            }
            set {
                if ((object.ReferenceEquals(this.DownField, value) != true)) {
                    this.DownField = value;
                    this.RaisePropertyChanged("Down");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Left {
            get {
                return this.LeftField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftField, value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Right {
            get {
                return this.RightField;
            }
            set {
                if ((object.ReferenceEquals(this.RightField, value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretKey {
            get {
                return this.SecretKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretKeyField, value) != true)) {
                    this.SecretKeyField = value;
                    this.RaisePropertyChanged("SecretKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Up {
            get {
                return this.UpField;
            }
            set {
                if ((object.ReferenceEquals(this.UpField, value) != true)) {
                    this.UpField = value;
                    this.RaisePropertyChanged("Up");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CaveService1.ICave")]
    public interface ICave {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/Init", ReplyAction="http://tempuri.org/ICave/InitResponse")]
        GameMICGOR.CaveService1.Location Init(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/Init", ReplyAction="http://tempuri.org/ICave/InitResponse")]
        System.Threading.Tasks.Task<GameMICGOR.CaveService1.Location> InitAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/Move", ReplyAction="http://tempuri.org/ICave/MoveResponse")]
        GameMICGOR.CaveService1.Location Move(int kierunek, string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/Move", ReplyAction="http://tempuri.org/ICave/MoveResponse")]
        System.Threading.Tasks.Task<GameMICGOR.CaveService1.Location> MoveAsync(int kierunek, string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/UserKey", ReplyAction="http://tempuri.org/ICave/UserKeyResponse")]
        int UserKey(int kierunek, string secretKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICave/UserKey", ReplyAction="http://tempuri.org/ICave/UserKeyResponse")]
        System.Threading.Tasks.Task<int> UserKeyAsync(int kierunek, string secretKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaveChannel : GameMICGOR.CaveService1.ICave, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaveClient : System.ServiceModel.ClientBase<GameMICGOR.CaveService1.ICave>, GameMICGOR.CaveService1.ICave {
        
        public CaveClient() {
        }
        
        public CaveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameMICGOR.CaveService1.Location Init(string playerName) {
            return base.Channel.Init(playerName);
        }
        
        public System.Threading.Tasks.Task<GameMICGOR.CaveService1.Location> InitAsync(string playerName) {
            return base.Channel.InitAsync(playerName);
        }
        
        public GameMICGOR.CaveService1.Location Move(int kierunek, string playerName) {
            return base.Channel.Move(kierunek, playerName);
        }
        
        public System.Threading.Tasks.Task<GameMICGOR.CaveService1.Location> MoveAsync(int kierunek, string playerName) {
            return base.Channel.MoveAsync(kierunek, playerName);
        }
        
        public int UserKey(int kierunek, string secretKey) {
            return base.Channel.UserKey(kierunek, secretKey);
        }
        
        public System.Threading.Tasks.Task<int> UserKeyAsync(int kierunek, string secretKey) {
            return base.Channel.UserKeyAsync(kierunek, secretKey);
        }
    }
}
