//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMICGOR.PalantirWCFService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/ObjectManager.Models")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gold {
            get {
                return this.GoldField;
            }
            set {
                if ((this.GoldField.Equals(value) != true)) {
                    this.GoldField = value;
                    this.RaisePropertyChanged("Gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PalantirWCFService1.IPalantirWCF")]
    public interface IPalantirWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalantirWCF/SetPlayerRank", ReplyAction="http://tempuri.org/IPalantirWCF/SetPlayerRankResponse")]
        void SetPlayerRank(string name, int gold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalantirWCF/SetPlayerRank", ReplyAction="http://tempuri.org/IPalantirWCF/SetPlayerRankResponse")]
        System.Threading.Tasks.Task SetPlayerRankAsync(string name, int gold);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalantirWCF/GetRanks", ReplyAction="http://tempuri.org/IPalantirWCF/GetRanksResponse")]
        GameMICGOR.PalantirWCFService1.Position[] GetRanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalantirWCF/GetRanks", ReplyAction="http://tempuri.org/IPalantirWCF/GetRanksResponse")]
        System.Threading.Tasks.Task<GameMICGOR.PalantirWCFService1.Position[]> GetRanksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPalantirWCFChannel : GameMICGOR.PalantirWCFService1.IPalantirWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PalantirWCFClient : System.ServiceModel.ClientBase<GameMICGOR.PalantirWCFService1.IPalantirWCF>, GameMICGOR.PalantirWCFService1.IPalantirWCF {
        
        public PalantirWCFClient() {
        }
        
        public PalantirWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PalantirWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalantirWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalantirWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetPlayerRank(string name, int gold) {
            base.Channel.SetPlayerRank(name, gold);
        }
        
        public System.Threading.Tasks.Task SetPlayerRankAsync(string name, int gold) {
            return base.Channel.SetPlayerRankAsync(name, gold);
        }
        
        public GameMICGOR.PalantirWCFService1.Position[] GetRanks() {
            return base.Channel.GetRanks();
        }
        
        public System.Threading.Tasks.Task<GameMICGOR.PalantirWCFService1.Position[]> GetRanksAsync() {
            return base.Channel.GetRanksAsync();
        }
    }
}
